baseurl = "https://christopherjunk.netlify.com/"
relativeurls = false
languageCode = "en-us"
title = "Christopher Junk"
theme = "hugo-prof"
googleAnalytics = "UA-135658780-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
uglyURLS = false
enableEmoji = true
blogdir = "blog"

[permalinks]
    post = "blog/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
#[[menu.main]]           # comment out this row, plus the name, url, and weight to omit  
  # name = "Research"    
  # url = "/research/"
  # weight = 2
#[[menu.main]]           # comment out this row, plus the name, url, and weight to omit 
  # name = "Teaching"
  # url = "/teaching/"
  # weight = 3
[[menu.main]]
  name = "Dissertation"
  url = "/dissertation"
  weight = 2
[[menu.main]]           # comment out this row, plus the name, url, and weight to omit 
    name = "Blog"
    url = "/blog/"
    weight = 4
[[menu.main]]
    name = "CV"
    url = "/christopherjunk_resume.pdf"
    weight = 5

[params]
    description = "I am a PhD student in political science at the University of Iowa." 
    subtitle = "PhD candidate. Data science and analysis. Non-state actor violence. Machine learning, applied statistics."
    home_text = """I study the dynamic relationship between terrorism, insurgency, and state use of power. More specifically,
    I have research projects that focus on (1) when democracies resort to repression as a response to violent and 
    nonviolent dissent, (2) how the incidence and lethality of terrorism affects support for the central 
    government in Spain, and (3) my dissertation implements machine learning strategies to predict the occurence,
    lethality, and locaiton of terrorism.
    
    \nMy Methodological interests include time series analysis, networks analysis, multilevel modeling, 
    survival analysis, and machine learning. My proficiency in statistical software is strongest in R and Stata, 
    but improving in Python.
    
    \nYou can see my [University of Iowa webpage here](https://clas.uiowa.edu/polisci/people/christopher-junk). 
    """

    author = "Christopher Junk"
    dateFormat = "2006/01/02"
    email = "christopher-hollis@uiowa.edu"
    github_username = "junkpolisci"
    twitter_username = "@Junk_polisci"  # leave empty quotes to omit
    #gscholar_code = ""        # leave empty quotes to omit    
    university = "https://clas.uiowa.edu/polisci/people/christopher-junk"

    page_color = "white"
    text_color = "black"
    link_color = "rgb(0, 0, 152)"
    hover_color = "rgb(255, 102, 0)"


    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
